In [2]:
import pandas as pd
import numpy as np

In [3]:
all_states = pd.read_csv('csv/a23.csv')

In [4]:
all_states

    PA_CODUNI  PA_GESTAO  PA_UFMUN  ...  PA_MNDIF  PA_VALAPR             State
0   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
1   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
2   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
3   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
4   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
5   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
6   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
7   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
8   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
9   3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
10  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
11  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
12  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
13  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
14  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
15  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
16  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
17  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
18  3065383.0   270240.0  270240.0  ...       0.0       2.81           Alagoas
19  2013916.0   130260.0  130260.0  ...       1.0      24.20          Amazonas
20  2013916.0   130260.0  130260.0  ...       0.0      24.20          Amazonas
21  2014610.0   130260.0  130260.0  ...       0.0      37.95          Amazonas
22  9507930.0   290000.0  291080.0  ...       1.0      10.00             Bahia
23  9507930.0   290000.0  291080.0  ...       1.0      10.00             Bahia
24  9507930.0   290000.0  291080.0  ...       1.0      10.00             Bahia
25  9507930.0   290000.0  291080.0  ...       1.0      10.00             Bahia
26  9507930.0   290000.0  291080.0  ...       1.0      10.00             Bahia
27  7978642.0   530000.0  530010.0  ...       0.0     268.75  Distrito Federal
28  7978642.0   530000.0  530010.0  ...       0.0     268.75  Distrito Federal
29  7978642.0   530000.0  530010.0  ...       0.0     268.75  Distrito Federal
30  7978642.0   530000.0  530010.0  ...       0.0     268.75  Distrito Federal
31  7530005.0   150680.0  150680.0  ...       1.0      11.00              Pará
32  7530005.0   150680.0  150680.0  ...       0.0      11.00              Pará
33        NaN        NaN       NaN  ...       NaN        NaN           Roraima
34        NaN        NaN       NaN  ...       NaN        NaN         São Paulo
35  2705680.0   354980.0  354980.0  ...       0.0       0.00         São Paulo
36  2705680.0   354980.0  354980.0  ...       0.0       1.00         São Paulo
37        NaN        NaN       NaN  ...       NaN        NaN         São Paulo
38        NaN        NaN       NaN  ...       NaN        NaN         São Paulo
39        NaN        NaN       NaN  ...       NaN        NaN         São Paulo
40  9242295.0   351880.0  351880.0  ...       0.0      11.00         São Paulo
41        NaN        NaN       NaN  ...       NaN        NaN         São Paulo
42        NaN        NaN       NaN  ...       NaN        NaN         São Paulo
43  9242295.0   351880.0  351880.0  ...       0.0       0.00         São Paulo
44  9242295.0   351880.0  351880.0  ...       0.0      11.00         São Paulo
45        NaN        NaN       NaN  ...       NaN        NaN         São Paulo
46        NaN        NaN       NaN  ...       NaN        NaN         São Paulo
47  9492380.0   351880.0  351880.0  ...       0.0      11.00         São Paulo
48  9492380.0   351880.0  351880.0  ...       0.0       0.00         São Paulo

[49 rows x 22 columns]

### Change the numeric value to string

In [4]:
columns_to_convert = [
    'PA_CODUNI', 'PA_GESTAO', 'PA_UFMUN', 'PA_TPUPS', 'PA_TIPPRE', 'PA_CNSMED', 'PA_MVM',
    'PA_CMP', 'PA_PROC_ID', 'PA_CBOCOD', 'PA_MUNPCN', 'PA_UFDIF', 'PA_MNDIF'
]

# Fill NaN with a placeholder, convert to the closest equivalent integer type that supports NaN, then to string
for column in columns_to_convert:
    if column in all_states.columns:
        all_states[column] = pd.to_numeric(all_states[column], errors='coerce').astype('Int64').astype('string')

# Replace all NaN values with '<NA>' explicitly for display purposes
all_states = all_states.fillna('0')

all_states.head()

  PA_CODUNI PA_GESTAO PA_UFMUN PA_TPUPS  ... PA_UFDIF PA_MNDIF PA_VALAPR    State
0   3065383    270240   270240       36  ...        0        0      2.81  Alagoas
1   3065383    270240   270240       36  ...        0        0      2.81  Alagoas
2   3065383    270240   270240       36  ...        0        0      2.81  Alagoas
3   3065383    270240   270240       36  ...        0        0      2.81  Alagoas
4   3065383    270240   270240       36  ...        0        0      2.81  Alagoas

[5 rows x 22 columns]

### Change PA_SEXO

In [5]:
# Replace values in 'PA_SEXO' column
all_states['PA_SEXO'] = all_states['PA_SEXO'].replace({'F': 'Mulher', 'M': 'Homem'})

### Change PA_RACACOR

In [6]:
# Define the mapping of codes to labels
racacor_mapping = {
    1: 'Branca',
    2: 'Preta',
    3: 'Parda',
    4: 'Amarela',
    5: 'Indígena',
    99: 'Sem informação'
}

# Replace the codes in 'PA_RACACOR' with the descriptive labels
all_states['PA_RACACOR'] = all_states['PA_RACACOR'].replace(racacor_mapping)

### Change the values of PA_UFDIF, PA_MNDIF

In [7]:
# Replace values in 'PA_UFDIF' column
all_states['PA_UFDIF'] = all_states['PA_UFDIF'].replace({'0': 'mesma UF', '1': 'UF diferente'})

# Replace values in 'PA_MNDIF' column
all_states['PA_MNDIF'] = all_states['PA_MNDIF'].replace({'0': 'mesmo município', '1': 'município diferente'})

### Rename the columns

In [8]:
# Mapping of old column names to new descriptive names
column_descriptions = {
    'PA_CODUNI': "Código do Estabelecimento no CNES",
    'PA_GESTAO': "Código da Unidade da Federação (IBGE) + Código do Município (IBGE) do Gestor, ou UF0000 se o estabelecimento estiver sob Gestão Estadual",
    'PA_UFMUN': "Unidade da Federação + Código do Município onde está localizado o estabelecimento",
    'PA_TPUPS': "Tipo de Estabelecimento",
    'PA_TIPPRE': "Tipo de Prestador",
    'PA_MVM': "Data de Processamento / Movimento (AAAAMM)",
    'PA_CMP': "Data da Realização do Procedimento / Competência (AAAAMM)",
    'PA_PROC_ID': "Código do Procedimento Ambulatorial",
    'PA_CNSMED': "Número do CNS (Cartão Nacional de Saúde) do profissional de saúde executante",
    'PA_CBOCOD': "Código da Ocupação do profissional na Classificação Brasileira de Ocupações (Ministério do Trabalho)",
    'PA_CIDPRI': "Código da CID Primária",
    'PA_IDADE': "Idade do paciente em anos",
    'PA_SEXO': "Sexo do paciente",
    'PA_RACACOR': "Raça/Cor do paciente",
    'PA_MUNPCN': "Código da Unidade da Federação + Código do Município de residência do paciente ou do estabelecimento, caso não se tenha a identificação do paciente",
    'PA_UFDIF': "Indica se a UF de residência do paciente é diferente da UF de localização do estabelecimento",
    'PA_MNDIF': "Indica se o município de residência do paciente é diferente do município de localização do estabelecimento",
    'PA_QTDPRO': "Quantidade Produzida (APRESENTADA)",
    'PA_QTDAPR': "Quantidade Aprovada do procedimento",
    'PA_VALPRO': "Valor Produzido (APRESENTADO)",
    'PA_VALAPR': "Valor Aprovado do procedimento",
    'State': "Estado"
}

# Rename columns in the dataframe
all_states_renamed = all_states.rename(columns=column_descriptions)

all_states_renamed.head()

  Código do Estabelecimento no CNES  ...   Estado
0                           3065383  ...  Alagoas
1                           3065383  ...  Alagoas
2                           3065383  ...  Alagoas
3                           3065383  ...  Alagoas
4                           3065383  ...  Alagoas

[5 rows x 22 columns]

In [9]:
# Exclude specific columns from the NaN check
excluded_columns = ['Estado']  # Assuming 'Estado' or its new name needs to be excluded from the check
included_columns = [col for col in all_states_renamed.columns if col not in excluded_columns]

for col in included_columns:
    all_states_renamed[col] = all_states_renamed[col].astype(str).str.lower()  # Convert each value to string and lowercase

# Redefine the condition to identify rows to remove, without using applymap
rows_to_remove_adjusted = (all_states_renamed[included_columns] == 'nan').all(axis=1)

# Remove these rows from the original DataFrame
all_states_renamed_cleaned = all_states_renamed.loc[~rows_to_remove_adjusted]

In [10]:
all_states_renamed_cleaned.head()

  Código do Estabelecimento no CNES  ...   Estado
0                           3065383  ...  Alagoas
1                           3065383  ...  Alagoas
2                           3065383  ...  Alagoas
3                           3065383  ...  Alagoas
4                           3065383  ...  Alagoas

[5 rows x 22 columns]

In [11]:
import unicodedata

all_states_final = all_states_renamed_cleaned.copy()

# Function to remove accents from a string
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

# Apply the function to the 'Estado' column to remove accents
all_states_final['Estado'] = all_states_final['Estado'].apply(remove_accents)

# Set the 'Estado' column as the index
all_states_final.set_index('Estado', inplace=True)

# Confirm changes by displaying the first few rows
all_states_final.head()

        Código do Estabelecimento no CNES  ... Valor Aprovado do procedimento
Estado                                     ...
Alagoas                           3065383  ...                           2.81
Alagoas                           3065383  ...                           2.81
Alagoas                           3065383  ...                           2.81
Alagoas                           3065383  ...                           2.81
Alagoas                           3065383  ...                           2.81

[5 rows x 21 columns]

### Exporting the file

In [12]:
final_csv_path = 'csv_a23/a23_cleaned.csv'
final_excel_path = 'a23_cleaned.xlsx'

# Save to CSV
all_states_final.to_csv(final_csv_path)

# Save to Excel
all_states_final.to_excel(final_excel_path)

final_csv_path, final_excel_path

('csv_a23/a23_cleaned.csv', 'a23_cleaned.xlsx')

In [13]:
# Código do Estabelecimento no CNES
# Código da Unidade da Federação (IBGE) + Código do Município (IBGE) do Gestor, ou UF0000 se o estabelecimento estiver sob Gestão Estadua
#  Unidade da Federação + Código do Município onde está localizado o estabelecimento
# Tipo de Estabelecimento
# Tipo de Prestador
# Código do Procedimento Ambulatorial
# Número do CNS (Cartão Nacional de Saúde) do profissional de saúde executante
# Código da Ocupação do profissional na Classificação Brasileira de Ocupações (Ministério do Trabalho)
# Código da Unidade da Federação + Código do Município de residência do paciente ou do estabelecimento, caso não se tenha a identificação do paciente